import assert from 'node:assert/strict';
import fs from 'node:fs';
import {pathToFileURL} from 'node:url';
const root=process.env.CAD_REVIEW_ROOT || process.cwd();
const mod=await import(pathToFileURL(root+'/runtime/cad/index.js'));
const commands=await import(pathToFileURL(root+'/core/commands/cad/index.js'));
const {DocumentAuthority,DocumentSessionClient,DirectSessionTransport,WorkerSessionTransport,RevisionQueue,EnvelopeType,validateEnvelope,createRequestEnvelope}=mod;
const {MoveEntitiesCommand}=commands;
const source=new TextEncoder().encode('0\r\nSECTION\r\n2\r\nHEADER\r\n9\r\n$ACADVER\r\n1\r\nAC1015\r\n0\r\nENDSEC\r\n0\r\nSECTION\r\n2\r\nENTITIES\r\n0\r\nLINE\r\n5\r\n10\r\n8\r\n0\r\n10\r\n0\r\n20\r\n0\r\n30\r\n0\r\n11\r\n10\r\n21\r\n0\r\n31\r\n0\r\n0\r\nENDSEC\r\n0\r\nEOF\r\n');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function bounded(p){let timer;try{return await Promise.race([p,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('request did not settle within 150ms')),150)})]);}finally{clearTimeout(timer);}}
function port(){let listener;return {sent:[],mode:'controlled',onMessage(fn){listener=fn;return ()=>{listener=null;}},send(e){this.sent.push(e)},emit(e){listener?.(e)},terminate(){listener=null}};}
const tests=[];const check=(id,fn)=>tests.push([id,fn]);
check('A04-ISOLATION',async()=>{const t=new DirectSessionTransport();try{t.authority.open({source,documentId:'new'});let reply; t.onMessage(e=>reply=e);t.send(createRequestEnvelope({type:EnvelopeType.COMMAND_REQUEST,documentId:'old',payload:{command:new MoveEntitiesCommand(['dxf:entity:10'],5,0)}}));await delay(20);assert.equal(t.authority.sourceRevision,0);assert.equal(t.authority.document.entities[0].geometry.start.x,0);assert.equal(reply.type,EnvelopeType.ERROR_RESPONSE);}finally{t.terminate()}});
check('A04-CANCEL-QUEUED',async()=>{const c=new DocumentSessionClient();try{await c.openDocument({source});c.transport.queue.enqueue(()=>delay(50));const p=c.query('SUMMARY');const result=p.then(()=>false,e=>e.code==='REQUEST_CANCELLED');const id=[...c.pendingRequests.keys()][0];assert.equal(await c.cancelRequest(id),true);assert.equal(await bounded(result),true);assert.equal(c.pendingRequests.size,0);}finally{c.dispose()}});
check('A04-CANCEL-HOST-REPLY',async()=>{const t=new DirectSessionTransport();try{t.authority.open({source,documentId:'D'});t.queue.enqueue(()=>delay(50));const id='queued';let response;t.onMessage(e=>{if(e.requestId===id)response=e});t.send(createRequestEnvelope({type:EnvelopeType.QUERY_REQUEST,documentId:'D',requestId:id,payload:{queryType:'SUMMARY'}}));t.send(createRequestEnvelope({type:EnvelopeType.CANCEL_REQUEST,documentId:'D',payload:{targetRequestId:id}}));await delay(30);assert.equal(response?.error?.code,'REQUEST_CANCELLED');assert.equal(t.queue.cancelledRequestIds.size,0);}finally{t.terminate()}});
check('A04-CANCEL-COMMITTED',async()=>{const c=new DocumentSessionClient();try{await c.openDocument({source});const t=c.transport;const emit=t._emit.bind(t);let held;t._emit=e=>{if(e.type===EnvelopeType.COMMAND_RESPONSE)held=e;else emit(e)};const pending=c.executeCommand(new MoveEntitiesCommand(['dxf:entity:10'],5,0));const result=pending.then(v=>v,e=>({error:e.code}));await delay(10);assert.equal(t.authority.sourceRevision,1);assert.equal(await c.cancelRequest(held.requestId),false);emit(held);assert.equal((await bounded(result)).sourceRevision,1);}finally{c.dispose()}});
check('A04-OPEN-RACE',async()=>{const t=port(),c=new DocumentSessionClient({transport:t});try{const a=c.openDocument({documentId:'A'}).then(v=>v,e=>({error:e.code}));const b=c.openDocument({documentId:'B'}).then(v=>v,e=>({error:e.code}));const [ra,rb]=t.sent;t.emit({type:EnvelopeType.OPEN_RESPONSE,requestId:rb.requestId,documentId:'B',sourceRevision:0,data:{documentId:'B',sourceRevision:0}});await delay(0);t.emit({type:EnvelopeType.OPEN_RESPONSE,requestId:ra.requestId,documentId:'A',sourceRevision:0,data:{documentId:'A',sourceRevision:0}});assert.equal((await bounded(a)).error,'REQUEST_CANCELLED');assert.equal((await bounded(b)).documentId,'B');assert.equal(c.documentId,'B');}finally{c.dispose()}});
check('A04-CLOSE-PENDING-OPEN',async()=>{const t=port(),c=new DocumentSessionClient({transport:t});try{const p=c.openDocument({documentId:'A'}).then(v=>v,e=>({error:e.code}));const req=t.sent[0];const close=c.closeDocument();const closeRequest=t.sent.at(-1);if(closeRequest.type===EnvelopeType.CLOSE_REQUEST)t.emit({type:EnvelopeType.CLOSE_RESPONSE,requestId:closeRequest.requestId,documentId:null,sourceRevision:0,data:{closed:true}});await close;t.emit({type:EnvelopeType.OPEN_RESPONSE,requestId:req.requestId,documentId:'A',sourceRevision:0,data:{documentId:'A',sourceRevision:0}});assert.equal((await bounded(p)).error,'REQUEST_CANCELLED');assert.equal(c.isReady,false);}finally{c.dispose()}});
check('A04-REPLAY-REVISION',async()=>{const c=new DocumentSessionClient();try{await c.openDocument({source});await c.executeCommand(new MoveEntitiesCommand(['dxf:entity:10'],1,0),{transactionId:'one'});await c.executeCommand(new MoveEntitiesCommand(['dxf:entity:10'],1,0));await c.executeCommand(new MoveEntitiesCommand(['dxf:entity:10'],1,0),{transactionId:'one'});assert.equal(c.currentRevision,2);}finally{c.dispose()}});
check('A04-PAYLOAD-IDENTITY',async()=>{const a=new DocumentAuthority();try{a.open({source});a.executeCommand({command:new MoveEntitiesCommand(['dxf:entity:10'],1,0),baseRevision:0,transactionId:'same',payloadDigest:'claimed'});assert.throws(()=>a.executeCommand({command:new MoveEntitiesCommand(['dxf:entity:10'],99,0),baseRevision:0,transactionId:'same',payloadDigest:'claimed'}),e=>e.code==='TRANSACTION_CONFLICT');assert.equal(a.sourceRevision,1);}finally{a.dispose()}});
check('A04-INNER-TRANSACTION-REPLAY',async()=>{const a=new DocumentAuthority();try{a.open({source});for(let i=0;i<2;i++){const cmd=new MoveEntitiesCommand(['dxf:entity:10'],1,0);cmd.transactionId='inner';a.executeCommand({command:cmd,baseRevision:i});}assert.equal(a.sourceRevision,1);}finally{a.dispose()}});
check('A04-EMPTY-UNDO',()=>{const a=new DocumentAuthority();try{a.open({source});a.undo(0);a.redo(0);assert.equal(a.sourceRevision,0);}finally{a.dispose()}});
check('A04-INVALID-REVISION',()=>{assert.equal(validateEnvelope({type:'COMMAND_REQUEST',requestId:'x',documentId:'D',baseRevision:NaN,payload:{}}).valid,false);assert.equal(validateEnvelope({type:'COMMAND_REQUEST',requestId:'x',documentId:'D',baseRevision:-1,payload:{}}).valid,false);assert.equal(validateEnvelope({type:'toString',requestId:'x'}).valid,false)});
check('A04-QUEUE-CANCEL-LEAK',async()=>{const q=new RevisionQueue();try{for(let i=0;i<100;i++)q.cancel('missing:'+i);assert.equal(q.cancelledRequestIds.size,0);}finally{q.dispose()}});
check('A04-SEND-FAILURE',async()=>{const t=port();t.send=()=>{throw new Error('postMessage failed')};const c=new DocumentSessionClient({transport:t});try{await assert.rejects(c.openDocument(),/postMessage failed/);assert.equal(c.pendingRequests.size,0);}finally{c.dispose()}});
check('A04-WORKER-PORT-LIFETIME',()=>{const listeners=new Set();const w={on(_,fn){listeners.add(fn)},off(_,fn){listeners.delete(fn)},postMessage(){},terminate(){}};const t=new WorkerSessionTransport(w);let observed;t.onMessage(e=>observed=e);for(const fn of listeners)fn({requestId:'raw',type:EnvelopeType.QUERY_RESPONSE});assert.equal(observed?.requestId,'raw');t.terminate();assert.equal(listeners.size,0)});
check('A04-SAVE-BUFFER',()=>{const a=new DocumentAuthority();try{a.open({source});const first=a.save();structuredClone(first.bytes.buffer,{transfer:[first.bytes.buffer]});assert.equal(first.bytes.byteLength,0);assert.deepEqual(a.save().bytes,source);}finally{a.dispose()}});
check('A04-FAILED-OPEN',()=>{const a=new DocumentAuthority();try{a.open({source,documentId:'original'});assert.throws(()=>a.open({source:{invalid:true},documentId:'replacement'}));assert.equal(a.documentId,'original');assert.equal(a.document.entities.length,1);}finally{a.dispose()}});
const results=[];for(const [id,fn]of tests){try{await fn();results.push({id,result:'PASS'});}catch(e){results.push({id,result:'FAIL',message:e.message});}}
const output={candidate:process.env.CAD_REVIEW_SHA || 'live-unattested',results};console.log(JSON.stringify(output,null,2));if(process.env.CAD_REVIEW_OUTPUT)fs.writeFileSync(process.env.CAD_REVIEW_OUTPUT,JSON.stringify(output,null,2));process.exitCode=results.some(r=>r.result==='FAIL')?1:0;
