import assert from 'node:assert/strict';import {test} from 'node:test';
import {DxfDocumentParser as Parser} from '../../../formats/dxf/parser/dxf-document-parser.js';import {DxfDocumentWriter as Writer} from '../../../formats/dxf/writer/dxf-document-writer.js';
import {DxfDocument} from '../../../formats/dxf/model/dxf-document.js';import {DxfEntity} from '../../../formats/dxf/model/dxf-entity.js';
import {DxfSpatialIndex} from '../../../formats/dxf/spatial/dxf-spatial-index.js';
import {CadSnapService} from '../../../core/geometry/cad-snaps.js';
import {GripManager} from '../../../core/grips/grip-manager.js';
import {CommandHistory} from '../../../core/commands/cad/index.js';
const check=test;
let fixtureId=0;class SampleEntity extends DxfEntity {constructor(p){super({...p,id:p.id || 'fixture:'+ (++fixtureId)});}}
const pt=(x,y,z=0)=>({x,y,z});const wrap=s=>'0\nSECTION\n2\nENTITIES\n'+s+'0\nENDSEC\n0\nEOF\n';const gm=new GripManager();const snap=new CadSnapService();
function textDoc(){return Parser.parse(wrap('0\nTEXT\n5\nA\n10\n100\n20\n100\n30\n5\n40\n1\n1\nAB\n'));}
function closedDoc(){return Parser.parse(wrap('0\nLWPOLYLINE\n5\nB\n70\n1\n90\n3\n10\n0\n20\n0\n10\n10\n20\n0\n10\n10\n20\n10\n'));}
check('positive control: LINE END snap',()=>{const e=new SampleEntity({type:'LINE',handle:'L',geometry:{start:pt(5,5),end:pt(10,5)}});assert.equal(snap.snap({entities:[e],cursorPoint:pt(5,5),tolerance:0.01,activeModes:['END']}).point.x,5);});
check('positive control: LINE grip + undo',()=>{const d=new DxfDocument();const e=new SampleEntity({type:'LINE',handle:'L',geometry:{start:pt(0,0),end:pt(10,0)}});d.addEntity(e);const h=new CommandHistory();const g=gm.extractEntityGrips(e).find(g=>g.role==='START');h.execute(gm.createGripEditCommand(g,pt(1,2)),d);assert.equal(e.geometry.start.x,1);h.undo(d);assert.equal(e.geometry.start.x,0);});
check('F108-01 parsed native TEXT grip anchor',()=>{const e=textDoc().entities[0];const g=gm.extractEntityGrips(e)[0];assert.equal(g.point.x,100,JSON.stringify(g.point));});
check('F108-01 grip movement persists native TEXT position',()=>{const d=textDoc();const e=d.entities[0];const h=new CommandHistory();const g=gm.extractEntityGrips(e)[0];h.execute(gm.createGripEditCommand(g,pt(120,130,5)),d);assert.equal(Parser.parse(Writer.write(d)).entities[0].geometry.insertionPoint.x,120);});
check('F108-02 parsed closed polyline closing segment NEA',()=>{const e=closedDoc().entities[0];const p=snap.calculateNearestPoint(e,pt(5,5));assert.ok(Math.hypot(p.x-5,p.y-5)<1e-8,JSON.stringify(p));});
check('F108-02 parsed closed polyline has closing MID grip',()=>{const e=closedDoc().entities[0];assert.equal(gm.extractEntityGrips(e).filter(g=>g.role==='MID').length,3);});
check('F108-03 deleted source cannot snap',()=>{const e=new SampleEntity({type:'LINE',handle:'D',geometry:{start:pt(0,0),end:pt(10,0)},state:{deleted:true}});assert.equal(snap.snap({entities:[e],cursorPoint:pt(0,0),tolerance:0.01,activeModes:['END']}),null);});
check('F108-04 snap accepts native DXF index port',()=>{const d=new DxfDocument();const e=new SampleEntity({type:'LINE',handle:'L',geometry:{start:pt(0,0),end:pt(10,0)}});d.addEntity(e);const ix=new DxfSpatialIndex();ix.loadFromDocument(d);assert.ok(snap.snap({entities:d.entities,spatialIndex:ix,cursorPoint:pt(0,0),tolerance:0.01,activeModes:['END']}),'native index candidates lost because service requires search/query');});
check('F108-05 2D grip edit preserves existing source elevation when Z omitted',()=>{const d=new DxfDocument();const e=new SampleEntity({type:'LINE',handle:'L',geometry:{start:pt(0,0,5),end:pt(10,0,5)}});d.addEntity(e);const h=new CommandHistory();const g=gm.extractEntityGrips(e).find(g=>g.role==='START');h.execute(gm.createGripEditCommand(g,{x:1,y:2}),d);assert.equal(e.geometry.start.z,5);});
check('F108-06 reject nonfinite grip coordinates before commit',()=>{const d=new DxfDocument();const e=new SampleEntity({type:'LINE',handle:'L',geometry:{start:pt(0,0),end:pt(10,0)}});d.addEntity(e);const h=new CommandHistory();const g=gm.extractEntityGrips(e).find(g=>g.role==='START');try{h.execute(gm.createGripEditCommand(g,{x:NaN,y:Infinity}),d);}catch{}assert.equal(e.geometry.start.x,0,'NaN/Infinity accepted as valid numbers');});
check('F108-07 INT snap retains common source plane',()=>{const a=new SampleEntity({type:'LINE',handle:'A',geometry:{start:pt(-1,0,5),end:pt(1,0,5)}});const b=new SampleEntity({type:'LINE',handle:'B',geometry:{start:pt(0,-1,5),end:pt(0,1,5)}});assert.equal(snap.snap({entities:[a,b],cursorPoint:pt(0,0,5),activeModes:['INT'],tolerance:0.01}).point.z,5);});
check('F108-08 indexed snap avoids full-document iteration',()=>{const near=new SampleEntity({type:'LINE',handle:'NEAR',geometry:{start:pt(0,0),end:pt(10,0)}});let reads=0;const far={get id(){reads++;return 'FAR';},type:'LINE',geometry:{start:pt(1000,0),end:pt(1001,0)}};const entities=[near,...Array(10000).fill(far)];snap.snap({entities,entityIndex:new Map([[near.id,near]]),spatialIndex:{search:()=>[{id:near.id}]},cursorPoint:pt(0,0),tolerance:1,activeModes:['END']});assert.equal(reads,0,`far entity ID reads=${reads}; lookup should use bounded candidates`);});
