import assert from 'node:assert/strict';import {test} from 'node:test';
import {DxfDocument} from '../../../formats/dxf/model/dxf-document.js';import {DxfEntity} from '../../../formats/dxf/model/dxf-entity.js';import {DxfBlock} from '../../../formats/dxf/model/dxf-block.js';
import {CommandHistory} from '../../../core/commands/cad/index.js';
import {TrimEntitiesCommand,OffsetCommand,ExplodeCommand,JoinCommand,FilletCommand} from '../../../core/commands/cad/edit-commands/index.js';
import {getEntitySegments} from '../../../core/geometry/cad-intersections.js';
const check=test;
const pt=(x,y,z=0)=>({x,y,z});const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`expected ${b}, got ${a}`);
function setup(){return {d:new DxfDocument(),h:new CommandHistory()};}function add(d,type,geometry,extra={}){const e=new DxfEntity({type,geometry,...extra});d.addEntity(e);return e;}
function line(d,a,b){return add(d,'LINE',{start:a,end:b});}
function trimCase(){const {d,h}=setup();const c=add(d,'CIRCLE',{center:pt(0,0),radius:10});const cutter=line(d,pt(-20,0),pt(20,0));h.execute(new TrimEntitiesCommand({entityId:c.id,cuttingEdgeIds:[cutter.id],clickPoint:pt(0,10)}),d);return {d,h,c};}
check('positive control: Trim converts circle to ARC',()=>{assert.equal(trimCase().c.type,'ARC');});
check('positive control: straight line Offset distance',()=>{const {d,h}=setup();const l=line(d,pt(0,0),pt(10,0));const cs=h.execute(new OffsetCommand({entityId:l.id,distance:2,sidePoint:pt(0,5)}),d);near(d.getEntity(cs.added[0].entityId).geometry.start.y,2);});
check('positive control: circle Trim undo restores native type',()=>{const {d,h,c}=trimCase();h.undo(d);assert.equal(c.type,'CIRCLE');assert.equal(c.geometry.startAngle,undefined);});
check('F107-01 Trim removes picked parameter interval, not nearest midpoint',()=>{const {d,h}=setup();const l=line(d,pt(0,0),pt(100,0));const a=line(d,pt(90,-1),pt(90,1));const b=line(d,pt(91,-1),pt(91,1));const cs=h.execute(new TrimEntitiesCommand({entityId:l.id,cuttingEdgeIds:[a.id,b.id],clickPoint:pt(89,0)}),d);near(l.geometry.start.x,90);assert.equal(cs.added.length,0);});
check('F107-02 kernel bulge ARC passes through original endpoints',()=>{const e=new DxfEntity({type:'LWPOLYLINE',geometry:{vertices:[{...pt(0,0),bulge:1},pt(2,0)]}});const a=getEntitySegments(e)[0];near(a.center.y,0);near(Math.hypot(a.center.x,a.center.y),a.radius);});
check('F107-02 exploded bulge ARC retains original geometry',()=>{const {d,h}=setup();const e=add(d,'LWPOLYLINE',{vertices:[{...pt(0,0),bulge:1},pt(2,0)]});const arc=h.execute(new ExplodeCommand([e.id]),d).added[0];near(d.getEntity(arc.entityId).geometry.center.y,0);});
check('F107-03 Offset must preserve bulge or explicitly reject',()=>{const {d,h}=setup();const e=add(d,'LWPOLYLINE',{vertices:[{...pt(0,0),bulge:1},pt(2,0)]});let cs;try{cs=h.execute(new OffsetCommand({entityId:e.id,distance:0.25,sidePoint:pt(1,-3)}),d);}catch{return;}assert.ok(!cs.added.length||Math.abs(d.getEntity(cs.added[0].entityId).geometry.vertices[0].bulge)>1e-8,'curved source silently replaced with straight chord');});
check('F107-04 Explode INSERT preserves child bulge metadata',()=>{const {d,h}=setup();const leaf=new DxfEntity({type:'LWPOLYLINE',geometry:{vertices:[{...pt(0,0),bulge:1,startWidth:0.1,endWidth:0.2},pt(2,0)]}});d.addBlock(new DxfBlock({name:'B',entities:[leaf]}));const e=add(d,'INSERT',{insertionPoint:pt(100,0),scale:pt(1,1,1)},{attributes:{blockName:'B'}});const out=h.execute(new ExplodeCommand([e.id]),d).added[0];assert.equal(d.getEntity(out.entityId).geometry.vertices[0].bulge,1);assert.equal(d.getEntity(out.entityId).geometry.vertices[0].startWidth,0.1);});
check('F107-05 Join preserves common source plane Z',()=>{const {d,h}=setup();const a=line(d,pt(0,0,5),pt(10,0,5));const b=line(d,pt(10,0,5),pt(20,0,5));const out=h.execute(new JoinCommand([a.id,b.id]),d).added[0];near(d.getEntity(out.entityId).geometry.elevation??d.getEntity(out.entityId).geometry.vertices[0].z??0,5);});
check('F107-06 Fillet ARC lies in same source plane as input lines',()=>{const {d,h}=setup();const a=line(d,pt(10,0,5),pt(0,0,5));const b=line(d,pt(0,0,5),pt(0,10,5));const out=h.execute(new FilletCommand({entity1Id:a.id,entity2Id:b.id,radius:2}),d).added[0];near(d.getEntity(out.entityId).geometry.center.z,5);});
check('F107-07 Join works when first selected segment is inside the chain',()=>{const {d,h}=setup();const middle=line(d,pt(1,0),pt(2,0));const first=line(d,pt(0,0),pt(1,0));const last=line(d,pt(2,0),pt(3,0));const cs=h.execute(new JoinCommand([middle.id,first.id,last.id]),d);assert.equal(cs.deleted.length,3,'all three segments are contiguous; algorithm only grows tail');});
